### ISSUE TITLE
Add overcommit.pp to deal with `Can't save in background: fork: Cannot allocate memory` ? 

### ISSUE THREAD

**Issue by v6** [arioch/puppet-redis#105]
I ran into this, recently: 

```
    [beta1redis213] out: 17662:M 28 Aug 12:39:14.595 # Can't save in background: fork: Cannot allocate memory
```

Turns out it's a common enough problem that someone put it in the ReDiS FAQ, and in somebody stuck a solution for it in their Puppet module for ReDiS: 

ReDiS FAQ on overcommit: http://redis.io/topics/faq#background-saving-is-failing-with-a-fork-error-under-linux-even-if-i39ve-a-lot-of-free-ram

https://github.com/giosakti/puppet-redis/blob/master/manifests/overcommit.pp

Is this over-engineering, or is it worth looking in to?

**Comment by petems** [comment]
Closed via #188
