### ISSUE TITLE
[Whishlist] Extend ulimit parameter to support limits.conf and systemd

### ISSUE THREAD

**Issue by mbaldessari** [arioch/puppet-redis#130]
It'd be grand if the ulimit parameter could be extended to set the nofile limits in:
- /etc/systemd/system/redis.service.d/limit.conf via the LimitNOFILE section
- /etc/security/limits.d/redis.conf

The former is for pure systemd OSes that do not make use of /etc/default/ and the latter is for when redis is invoked via a cluster manager (e.g. pacemaker, rgmanager)

**Comment by petems** [comment]
@mbaldessari Should be fairly trivial to implement! 😄 

I noticed you doing this here for the openstack project: https://github.com/openstack/puppet-tripleo/blob/f9efeb158261fbdad206ea072c4c628636c1a5f4/manifests/profile/pacemaker/database/redis.pp#L63

I should be able to implement that in the module natively 💃 

Is there anything else you want this module to do would help you with the Openstack stack?

**Comment by mbaldessari** [comment]
Thanks a lot, I'll try this out and remove my hack once this change trickles down ;)
