### ISSUE TITLE
Wrong redis.conf after c45049986a7fcb1c9a0591de123c6bf97c761355

### ISSUE THREAD

**Issue by amoralej** [arioch/puppet-redis#142]
After commit c45049986a7fcb1c9a0591de123c6bf97c761355 , a bunch of parameters in redis.conf are left without any value, for example:

syslog-facility
masterauth
...

If parameter is not passed: 

I'm using following puppet manifest:

class { '::redis':
  bind       => '0.0.0.0',
  port       => 6379,
  appendonly => true,
  daemonize  => false,
  unixsocket => false,
}

With puppet-redis before commit c45049986a7fcb1c9a0591de123c6bf97c761355, it work fine. After this commit redis doesn't start as redis.conf.

**Comment by petems** [comment]
Fixed in #https://github.com/arioch/puppet-redis/pull/143
