### ISSUE TITLE
Ubuntu 16.04 support?

### ISSUE THREAD

**Issue by lkthomas** [arioch/puppet-redis#146]
Any chance for this module support Ubuntu 16.04?

**Comment by arioch** [comment]
Have you tried running it on Ubuntu 16.04?
What seems to be going wrong or missing? Any errors messages or logs available?

**Comment by petems** [comment]
@lkthomas Our Acceptance tests run on Ubuntu 16.04 and it works ok 👍 https://travis-ci.org/arioch/puppet-redis/jobs/180936979

**Comment by arioch** [comment]
I've updated metadata.json: 4ea53ee263b8f7129c2e6eaf54789cf48a3fd884.
