### ISSUE TITLE
Ownership problem with Ubuntu redis-server

### ISSUE THREAD

**Issue by jerith** [arioch/puppet-redis#150]
On Ubuntu 14.04, `redis-server` has an init script that does `chown redis:redis $RUNDIR $PIDFILE` (where `RUNDIR=/var/run/redis` and `PIDFILE=$RUNDIR/redis-server.pid`) at startup. This causes puppet to "fix" the ownership of `/var/run/redis` (to `redis:root` unless `config_owner` and `config_group` have been set differently), which triggers a restart of `redis-server`, which changes the ownership of `/var/run/redis`, etc. forever.

Is it possible to tell puppet not to care about the owner or group of `/var/run/redis` beyond the initial creation?

**Comment by petems** [comment]
I think we can fix that easier by just changing the `$config_group` default on Ubuntu to Redis.

Can you try changing that in the code in your Ubuntu 14.04 machine and see if it changes anything else? So add a section in the params to change  `config_group` in Ubuntu 👍

**Comment by jerith** [comment]
My workaround was to set `redis::config_group` to `redis` in hiera, which seems to have sorted out the problem.

**Comment by jerith** [comment]
On debian jessie (which we also run), a stock install of `redis-server` (from jessie-backports, although I don't think that makes a difference) has both `/var/run/redis` and `/etc/redis/redis.conf` owned by `redis:redis`. `/etc/redis` and everything else inside it is owned by `root:root` with world-readable permissions.

**Comment by nvtkaszpir** [comment]
The same happens on debian wheezy.

**Comment by dominics** [comment]
> Can you try changing that in the code in your Ubuntu 14.04 machine and see if it changes anything else?

Can confirm (albeit with 16.04) that it changes the group of `/etc/redis`, `/etc/redis/redis.conf` and `/etc/default/redis-server`, not just `/var/run/redis`. Fine for me (I want to `CONFIG REWRITE` anyway) - but, in general, not isolated to `/var/run`.
