### ISSUE TITLE
add-apt-repository required on Ubuntu Xenial

### ISSUE THREAD

**Issue by tobias-urdin** [arioch/puppet-redis#154]
When running on Ubuntu Xenial and letting the module manage the repo it's trying to add Chris Lea's redis repo with add-apt-repository but if that command does not exist (it's not installed by default in Ubuntu iirc) it will fail.

``Error: Could not find command '/usr/bin/add-apt-repository'
Error: /Stage[main]/Redis::Preinstall/Apt::Ppa[ppa:chris-lea/redis-server]/Exec[add-apt-repository-ppa:chris-lea/redis-server]/returns: change from notrun to 0 failed: Could not find command '/usr/bin/add-apt-repository'``

Would this be something we should check using for example ensure_packages or should this be up to the user to make sure they have on their system?

I can submit a PR if it's OK.
Best regards

**Comment by dominics** [comment]
This should be handled by your `apt` module, not this one. For example, see the `apt::ppa::package_manage` option (https://forge.puppet.com/puppetlabs/apt#defined-type-aptppa), which should do exactly what you want if you set it to `true` (it defaults to `false`)

**Comment by tobias-urdin** [comment]
Since this module uses the `apt` module to manage the PPA repository for Ubuntu, would it make sense to modify https://github.com/arioch/puppet-redis/blob/master/manifests/preinstall.pp#L30 to take exactly what you mentioned into account?

`apt::ppa { $::redis::ppa_repo:
  package_manage => true
}`

**Comment by petems** [comment]
This is something that you should manage within your own roles and profiles, I don't want to add it in by default as it might cause conflicts.

You can also overwrite this config in your own code like so:

```puppet
Apt::ppa {
   package_manage => true,
}
```
