### ISSUE TITLE
CentOS 7 failed installing

### ISSUE THREAD

**Issue by DiegoGallegos4** [arioch/puppet-redis#156]
Getting this error when running puppet agent: 

![image](https://cloud.githubusercontent.com/assets/5933437/24685827/2e070eb6-196d-11e7-80cf-1d5a6e18a3e1.png)

To reproduce: 

`class{'redis': }`

all dependencies are installed.

**Comment by petems** [comment]
@DiegoGallegos4 Can you try the following code for me:

```puppet
class { '::redis':
  manage_repo => true,
}
```

Basically it's saying it can't find the redis package from the upstream repo, so you need to enable epel.

**Comment by petems** [comment]
This is resolved by the above code, as the acceptance test states. Closing.
