### ISSUE TITLE
Ubuntu 16.04 changed sentinel config filename

### ISSUE THREAD

**Issue by KlavsKlavsen** [arioch/puppet-redis#175]
so it now is supposed to be called /etc/redis/sentinel.conf

I couldn't find a nice way (without large restructuring) to fix this in params.pp.. I've moved to data-in-modules which makes it a lot easier to handle such exceptions.

**Comment by KlavsKlavsen** [comment]
and you're managing /etc/init.d/redis-sentinel - but since 16.04 is systemd - it uses the systemd file from the package - which points at /etc/redis/sentinel.conf

So perhaps a better fix - would be to just manage the systemd file? I'll gladly do a PR for that ?

**Comment by petems** [comment]
A PR to manage the systemd file would be greatly appreciated! 😄

**Comment by KlavsKlavsen** [comment]
can I use epp templates, or ?

**Comment by petems** [comment]
ERB for now, I want to get the last few features fixed before we move onto Puppet 4, like parameters only being included on certain versions and multiple instances of redis on one server.

**Comment by KlavsKlavsen** [comment]
I have it ready now.. will send PR tonight so you can give feedback (have to go from work now :)

**Comment by petems** [comment]
No problem, looking forward to it! 👍

**Comment by KlavsKlavsen** [comment]
https://github.com/arioch/puppet-redis/pull/176 - I choose to install systemd override when system is running systemd.. did not make sense to do it any other way IMHO :)

**Comment by petems** [comment]
Ok, looking at all the debian flavours out there (Deb 8, Ubuntu 14.04 - PPA and external, and 16.04 upstream) it looks like this should always be `/etc/redis/sentinel.conf`.

So I've opened a PR to fix it for all Debian flavour machines: https://github.com/arioch/puppet-redis/pull/184
