### ISSUE TITLE
Sentinel init/upstart file doesn't exist

### ISSUE THREAD

**Issue by antonlindstrom** [arioch/puppet-redis#18]
When trying to install sentinel (`class { 'redis::sentinel': }`) on Ubuntu 14.04, the following error appears:

    Error: /Stage[main]/Redis::Sentinel/Service[redis-sentinel]: Could not find init script or upstart conf file for 'redis-sentinel'

I would expect that there would be an init or upstart script in place that would start the sentinel service.

Building a template for the sentinel service should probably do the trick.

Thank you for an awesome module!

**Comment by arioch** [comment]
@cdent, could you please look into this?

**Comment by cdent** [comment]
Yeah, can do tomorrow. Up til now all my testing has been rpm-based distros. I'll take a look at Ubuntu tomorrow.

BTW: There should be yet another pull request on the sentinel support coming from one of my colleagues tomorrow: The way the sentinel.pp requires the redis package is flaky and not properly puppet idiomatic.

Clearly I have no idea what I'm doing ... :)

**Comment by antonlindstrom** [comment]
That sounds great, thanks!

**Comment by cdent** [comment]
In the long term I reckon this is a bug in debian, so I've [reported one there](http://bugs.debian.org/cgi-bin/bugreport.cgi?bug=775414).

In the short term I guess we need to stub in an init script of our own. What's the best way to do that?

**Comment by arioch** [comment]
@cdent, this should get you going pretty fast: https://github.com/jordansissel/pleaserun

**Comment by cdent** [comment]
Thanks. I'm going to pause on implementing this until #19 has resolved (more comments over there in a moment) as the place to hook in the changes will be more clear then.

**Comment by antonlindstrom** [comment]
Awesome, thanks!
