### ISSUE TITLE
Please cut a release

### ISSUE THREAD

**Issue by ghoneycutt** [arioch/puppet-redis#201]
In accordance with semver, could you please cut a new release when PR's are merged. It has been almost 6 months since the last release and I'm pinning to individual commit SHA's and trying to understand each commit to see if it is breaking things or not. I think this will help people consume and contribute to your module.

**Comment by petems** [comment]
Will do! 👍 

I've cut a 3.0.0 release, asking @arioch for a manual deploy right now as we haven't got the Travis auto-deploy magic working yet 🎆

**Comment by petems** [comment]
Done 👍 

https://forge.puppet.com/v3/files/arioch-redis-3.0.0.tar.gz
