### ISSUE TITLE
Releasing v3.0.1

### ISSUE THREAD

**Issue by EmilienM** [arioch/puppet-redis#205]
Could we please have a v3.0.1 release including:
https://github.com/arioch/puppet-redis/commit/464a04b9e6fa23d32c9deaa81776d1b6757c71fe

It would allow us to deploy the latest tag.
Thanks!

**Comment by EmilienM** [comment]
@arioch ping

**Comment by EmilienM** [comment]
Thanks

**Comment by petems** [comment]
When this is green, we should have an autodeployed 3.1.0 tag: https://travis-ci.org/arioch/puppet-redis/builds/234066145

**Comment by arioch** [comment]
It failed, so I've deployed manually. 
https://forge.puppet.com/arioch/redis/3.1.0/readme

To be continued.
