### ISSUE TITLE
Travis Forge Password Changed

### ISSUE THREAD

**Issue by petems** [arioch/puppet-redis#216]
https://travis-ci.org/arioch/puppet-redis/jobs/252498253

@arioch Can you have a look at this? Says the passwords wrong 😢

**Comment by jaredledvina** [comment]
@petems / @arioch  - Is this why release 3.2.0 isn't availible on https://forge.puppet.com/arioch/redis ?

**Comment by petems** [comment]
@jaredledvina Indeed, haven't been able to do a release since the password failed

**Comment by petems** [comment]
Fixed by @arioch 😄
