### ISSUE TITLE
[Feature Request] Redis::Instance - Set default unixsocket

### ISSUE THREAD

**Issue by tdotgreenshirt** [arioch/puppet-redis#226]
For the new implementation of separate Redis instances, if a unixsocket is not specified, each redis::instance will use the same .sock file. I'm not sure if this poses as an issue, but would like to submit a feature request to append each Redis instance name as the default value for the unixsocket attribute:
(e.g unixsocket => "/var/run/redis/redis-${instance}.sock",)

**Comment by petems** [comment]
Yeah, seems reasonable, feel free to open a PR 👍

**Comment by tdotgreenshirt** [comment]
Disregard. This is happening on the latest version of the module.
