### ISSUE TITLE
Can't use as slave bound to localhost

### ISSUE THREAD

**Issue by jarro2783** [arioch/puppet-redis#229]
Why is there a check that prevents using a slave that also binds to localhost: https://github.com/arioch/puppet-redis/blob/master/manifests/init.pp#L251?

I set up an instance with this configuration and it works fine.

**Comment by petems** [comment]
I think this was because before you couldn't have multiple redis instances on one host with this module, so it made sense then. But as you say, this isn't neccsary now 👍
