### ISSUE TITLE
puppet-redis requires outdated puppetlabs-apt module

### ISSUE THREAD

**Issue by llauren** [arioch/puppet-redis#232]
## General apology

I'm no expert in puppet nor git issues. Please be kind with my issue and me. Thank you.

## Affected versions

* arioch/puppet-redis 3.1.0
* puppetlabs/apt 4.1.0
* Puppet 4.10.5
* Ubuntu 16.04 LTS

## How to reproduce

`puppet module install arioch-redis` when current version of `puppetlabs-apt` is installed, or

`puppet module list --verbose` when modules are installed by `--force`.

## What am i seeing?

```
$ puppet module list --verbose
Warning: Module 'puppetlabs-apt' (v4.1.0) fails to meet some dependencies:
  'arioch-redis' (v3.1.0) requires 'puppetlabs-apt' (>=2.3.0 <3.0.0)
...
```

## Expected behaviour

A clean install.

## Suggest solution

Bump required maximum version of `puppetlabs-apt` to `<5.0.0`. Unfortunately i don't have the competency to actually tell whether there is code that isn't 4.x-compliant.

**Comment by petems** [comment]
Fixed by #237
