### ISSUE TITLE
Does not work with Debian 7.8 with redis version 2.4.14-1

### ISSUE THREAD

**Issue by confiq** [arioch/puppet-redis#24]
At least does not work out of box...
It says:

>Starting redis-server: 
>*** FATAL CONFIG FILE ERROR ***
>Reading the configuration file, at line 108
> 'stop-writes-on-bgsave-error yes'

or 
>Reading the configuration file, at line 122
> 'rdbchecksum yes'

v.2.4.14-1 is latest package for debian.
You might drop 2.4.X support ?

**Comment by arioch** [comment]
2.4.x has been unsupported for a while now.
2.6.x is probably the oldest version supported.
