### ISSUE TITLE
Inconsistent sentinel_package_name handling on Debian

### ISSUE THREAD

**Issue by eserte** [arioch/puppet-redis#253]
In https://github.com/arioch/puppet-redis/blob/6c28bc3/manifests/params.pp#L123  `$sentinel_package_name` is set for all Debian systems to `redis-sentinel`. But in https://github.com/arioch/puppet-redis/blob/2231d4d/manifests/sentinel.pp#L205 the `package` definition happens only for Ubuntu 16.04 and newer (and there's no support for real Debian systems like stretch and sid). This is causing errors on other Debian systems:
```
Error: Could not retrieve catalog from remote server: Error 500 on SERVER: Server Error: Invalid relationship: File[/etc/redis/sentinel.conf.puppet] { require => Package[redis-sentinel] }, because Package[redis-sentinel] doesn't seem to be in the catalog
```

I think the condition in sentinel.pp should be moved to params.pp, and the condition in sentinel.pp should be changed to a `unless defined Package[$package_name]` or so.

**Comment by petems** [comment]
@eserte I didn't know they'd changed the package in Stretch, I'll fix that in a PR 👍
