### ISSUE TITLE
Module v3.2.0 not published to forge

### ISSUE THREAD

**Issue by fatmcgav** [arioch/puppet-redis#255]
It looks like you have released v3.2.0 of module on Github, but that version hasn't been published to the Puppet Forge.
Latest available version is listed as 3.1.0: https://forge.puppet.com/arioch/redis

**Comment by dol** [comment]
Upvote

**Comment by arioch** [comment]
As requested: https://forge.puppet.com/arioch/redis/3.2.0/.

@dol rather than upvote you can just mail/slack me. Otherwise your msg gets cought in my filters like any other Github mail.
My address shouldn't be too hard to find... 😉

**Comment by petems** [comment]
Awesome, thanks @arioch! 😄

**Comment by dol** [comment]
@arioch Sorry. Will do in the future. Thanks.

**Comment by arioch** [comment]
No need to apologise, you didn't do anything wrong. 🍺
