### ISSUE TITLE
Default config_owner of redis

### ISSUE THREAD

**Issue by raiblue** [arioch/puppet-redis#39]
Hi again,
Maybe it would be better if default config_owner of Redis is 'redis'. redis.conf must be writable by Redis or Sentinel when a failover happens (I'm not sure exactly which one, redis or sentinel, handles this action) and config-rewrite works. In the module config_owner is 'root' for all OS types by now, which causes "CONFIG REWRITE failed: Permission denied" error in failover time. Also it seems that redis rpm's do this by default.

**Comment by arioch** [comment]
You're absolutely right.
Could you confirm 09f52cfda45ecd04f42b05f1b37b1e3a36154cd5 fixes this issue?

**Comment by raiblue** [comment]
Yes.
Thanks.
