### ISSUE TITLE
Commit edd7cb55931fe0336bfee475c738ac4b91308f98 seems to be pasting undef params into redis.conf

### ISSUE THREAD

**Issue by gfidente** [arioch/puppet-redis#41]
After commit edd7cb55931fe0336bfee475c738ac4b91308f98 , I seem to be getting undef params into the redis.conf file, like:

> syslog-facility undef
> slaveof undef
> masterauth undef
> requirepass undef
> maxmemory undef
> maxmemory-policy undef
> maxmemory-samples undef
> include undef

**Comment by gfidente** [comment]
> syslog-enabled yes

it should be "no" cause it is undef by default

**Comment by arioch** [comment]
@eoly could you take a quick look at this?

**Comment by cwolferh** [comment]
I'm also seeing this issue when declaring class {'::redis' ... (no hiera in my case).  It does not happen without https://github.com/arioch/puppet-redis/commit/edd7cb55931fe0336bfee475c738ac4b91308f98 .

**Comment by eoly** [comment]
@gfidente and @cwolferh,

Could I get the version of Puppet you are using?

My suspicion is that the scope.lookupvar function is evaluating to true even if the variable it is looking up is set to undef.

I'll do some more testing on my end and get back to you guys.

**Comment by eoly** [comment]
https://docs.puppetlabs.com/guides/templating.html#testing-for-undefined-variables

That link actually explains the problem. I'll submit a fix shortly.

**Comment by arioch** [comment]
@gfidente and @cwolferh could you please confirm this fixes the problem?

**Comment by cwolferh** [comment]
@arioch, confirmed, works for me.

**Comment by arioch** [comment]
Alright, thanks guys.
