### ISSUE TITLE
'manage_repo => true' causes run to fail because add-apt-repository command isn't available

### ISSUE THREAD

**Issue by patrick-minted** [arioch/puppet-redis#49]
I worked around this, but it really should be part of the setup.
Ubuntu 12.04

  package{'python-software-properties':
    ensure => installed
  } ->
  package{'software-properties-common':
    ensure => installed
  } ->
  class { 'redis':
    manage_repo => true,
    ...
  }

**Comment by arioch** [comment]
Feel free to wrap this into a patch and send me a pull request so you get to have the proper credits.

**Comment by petems** [comment]
The PPA resource installs the required package if you use the `package_manage` parameter: 
https://github.com/puppetlabs/puppetlabs-apt/blob/1b6e046bea87b388f957edf946af363279769c21/manifests/ppa.pp#L7

You can fix with the following added to your roles and profiles:

```puppet
Apt::Ppa {
  package_manage => true,
}
```

Adding this to the module would be a breaking change and might conflict with someones existing code, so will leave this as for future reference.
