### ISSUE TITLE
Redis service start fail on Debian stable (Wheezy 7.0)

### ISSUE THREAD

**Issue by stavrosicsd** [arioch/puppet-redis#52]
Debian Wheezy installs redis-server 2.4.14 which service never starts.

If you try to start the service you get the following error:
$ sudo service redis-server start
Starting redis-server: 
*** FATAL CONFIG FILE ERROR ***
Reading the configuration file, at line 110
>>> 'stop-writes-on-bgsave-error yes'
Bad directive or wrong number of arguments
failed

$ dpkg -l |grep redis
ii  redis-server                       2:2.4.14-1                    amd64        Persistent key-value database with network interface

**Comment by arioch** [comment]
Redis 2.4 is no longer supported by this module.
Please use the packages from [backports](https://packages.debian.org/wheezy-backports/redis-server) instead.
