### ISSUE TITLE
puppet-redis || every time when puppet runs, the service restarts

### ISSUE THREAD

**Issue by x86nick** [arioch/puppet-redis#59]
Hi Arioch,

As soon as puppet runs it overwrites the redis.conf and trigger the restart.
I am missing something here and  i am not sure how to tell puppet not to overwrite the redis.conf every time ?
# 

 # Note that you must specify a directory here, not a file name.
-dir "/var/lib/redis"
+dir /var/lib/redis/

 ################################# REPLICATION #################################

@@ -388,7 +390,7 @@
 # rewrite feature.

 auto-aof-rewrite-percentage 100
-auto-aof-rewrite-min-size 0
+auto-aof-rewrite-min-size   64min

 ################################ LUA SCRIPTING  ###############################

@@ -526,6 +528,3 @@
 # include /path/to/other.conf
 include /etc/redis/redis-custom.conf

-# Generated by CONFIG REWRITE
-slaveof x.x.x.x 6379
-min-slaves-to-write 1

Info: /Stage[main]/Redis::Config/File[/etc/redis/redis.conf]: Filebucketed /etc/redis/redis.conf to main with sum 24086ae26aeb2008676489bf49a48260
# Notice: /Stage[main]/Redis::Config/File[/etc/redis/redis.conf]/content: content changed '{md5}24086ae26aeb2008676489bf49a48260' to '{md5}fe6acd8504391c2f6a91304d4c1f3931'

**Comment by arioch** [comment]
That's pretty annoying.
Did you manually adjust the configuration at runtime?

**Comment by petems** [comment]
Closing as it's been over a year with no response, can re-open if needed
