### ISSUE TITLE
Cluster Support

### ISSUE THREAD

**Issue by cdenneen** [arioch/puppet-redis#62]
Any plan for cluster support in 3.0.0?
Also in using cluster might be useful to run a master/slave on each node?

Not sure how you'd handle running slave of master(not the master instance on that node) but that could be useful in creating a fully redundant cluster with no data loss.

**Comment by arioch** [comment]
Currently I have no short-term plans to implement this.
I'd love to but i simply don't have the time to do so.

Feel free to contribute. I'll gladly review and accept patches!

**Comment by elisiano** [comment]
+1

**Comment by arioch** [comment]
It's coming thanks to @claudio-walser (#67).
Would be awesome if you guys could give some early feedback.

**Comment by elisiano** [comment]
Looks good! I'm new to redis so I might be overlooking something but the cluster configuration is only one part. The actual operations need to be done either manually or with the redis-trib.rb utility shipped with redis. So maybe a provider would be needed for this. 
Nonetheless, it's a great starting point (at least the config can be done directly with the module instead of resorting to the $extra_config_file parameter).

**Comment by claudio-walser** [comment]
True, we handled it internally in a service script, taking advantage of the redis-trib.rb
Its kind of separated in our repo so i didnt implemented it in the redis module itself...

**Comment by arioch** [comment]
@claudio-walser could you maybe add a small redacted example of that redis-trib.rb script of yours to the readme? Or if it's too large add it in a directory "ext" and refer to it in the readme file.

**Comment by claudio-walser** [comment]
@arioch Sure i'll add that, think i will find some time today and you dont have to wait another 3 weeks :)

**Comment by vide** [comment]
@claudio-walser @arioch Did you put that little redis-trb.rb example somewhere? Thanks!

**Comment by petems** [comment]
Cluster support was merged in 4fb33b960a09bfb459eff20ee112bfc9e0a1c096 and released in 1.2.0

The implementation of the cluster with `redis-trib.rb` or other tools is another thing, if someone has an example it can be added in a seperate PR 😄

**Comment by vide** [comment]
I have a very crude `exec{}` hack to setup-up through with no human-intervention a basic cluster with `redis-trib.rb`, but I'm not sure it's ready for prime-time. I can prepare a PR in the next few days if you wish

**Comment by elisiano** [comment]
@vide: yes please!

**Comment by petems** [comment]
@vide that would be awesome, if it's a bit too hacky we could put it as a documentation example with the caveats on it 😄
