### ISSUE TITLE
  // , How do I change from powerstack.org repo if I need to? Should I just edit manifests/preinstall.pp? 

### ISSUE THREAD

**Issue by v6** [arioch/puppet-redis#68]
// , I want to do a trial adoption of this EXCELLENT Puppet module on some of our OpenStack machines.

Also, I may, later, want to run this on some legacy systems (I'm looking at you, CEntOS 6...). 

InfoSec may raise some an eyebrow at powerstack.org. 

If they do, I might want to switch out the the http://download.powerstack.org/6/ for an internal repo.

Should I just edit the https://github.com/arioch/puppet-redis/blob/master/manifests/preinstall.pp file, or is there a better way to switch this?

I can draft a pull request to make this more flexible, if desired.

**Comment by arioch** [comment]
Feel free to whip up a pull request. :+1:

**Comment by petems** [comment]
Powerstack has been removed, using normal upstream repos.

If you wish to use your own repo, simply set $manage_repo to false, and add your repo of choice in your profiles! 👍
