### ISSUE TITLE
  // , preinstall.pp fails on CEntOS 6.5 and Puppet Enterprise 2.7.

### ISSUE THREAD

**Issue by v6** [arioch/puppet-redis#72]
// , 

```err: Could not retrieve catalog from remote server: Error 400 on SERVER: undefined method `<' for :undef:Symbol at /etc/puppet/modules/redis/manifests/preinstall.pp:10 on node redis1```

Perhaps it's missing a fact, or something, but this seems like a bug. 

This may be related to CEntOS 6.5 using an older version of Facter, as here: 

http://serverfault.com/questions/528878/puppet-facter-how-to-determine-if-running-cent-6-or-cent-5

**Comment by v6** [comment]
// , UPDATE: I fixed this by changing line 10 of `/etc/puppet/modules/redis/manifests/preinstall.pp` from `if $::operatingsystemmajrelease < '7' {` to `if $::operatingsystemrelease < '7' {`. 

Do you think this is worth a pull request to allow older versions of Facter, like 1.6.13?

**Comment by v6** [comment]
// , Also, does this allow us to set an item like `tcp-keepalive 60` in the configuration file?

**Comment by arioch** [comment]
That's going to break facter 2 and above.
Unless you find a way to get around that I can't support that.

**Comment by v6** [comment]
// , Ah, got it. Let me see if I can find a way to support both. 

I checked https://docs.puppetlabs.com/facter/2.0/release_notes.html#breaking-changes, and it doesn't seem to list $::operatingsystemrelease.

**Comment by v6** [comment]
// , I can't figure out how this breaks facter 2 and above. I can test this later on a Vagrant box, though.

**Comment by petems** [comment]
PE 2.7 has been EOL for a long time, closing. 

https://puppet.com/misc/version-history
