### ISSUE TITLE
  // , Potential bug: `64min` should read `64mb`

### ISSUE THREAD

**Issue by v6** [arioch/puppet-redis#73]
// , The following section of a correct configuration file requires `64mb` as a default, not `64min`: 

    # Automatic rewrite of the append only file.
    # Redis is able to automatically rewrite the log file implicitly calling
    # BGREWRITEAOF when the AOF log size grows by the specified percentage.
    #
    # This is how it works: Redis remembers the size of the AOF file after the
    # latest rewrite (if no rewrite has happened since the restart, the size of
    # the AOF at startup is used).
    #
    # This base size is compared to the current size. If the current size is
    # bigger than the specified percentage, the rewrite is triggered. Also
    # you need to specify a minimal size for the AOF file to be rewritten, this
    # is useful to avoid rewriting the AOF file even if the percentage increase
    # is reached but it is still pretty small.
    #
    # Specify a percentage of zero in order to disable the automatic AOF
    # rewrite feature.

    auto-aof-rewrite-percentage 100
    auto-aof-rewrite-min-size 64mb

I found this problem in two areas: 

https://github.com/arioch/puppet-redis/search?utf8=%E2%9C%93&q=64min

**Comment by v6** [comment]
// , Can I make a pull request for this one?

**Comment by v6** [comment]
// , Also, is this, in fact, a bug?

**Comment by arioch** [comment]
That's a bug and is fixed in 2771a9d81beee9533bf26cf5200b4a7c812370bb.
Thanks for reporting.
