### ISSUE TITLE
redis.conf under /etc/redis.conf

### ISSUE THREAD

**Issue by tobiasschaber** [arioch/puppet-redis#81]
Hey,

is there a reason why the redis conf for RedHat systems is placed under:

/etc/redis.conf

instead of

/etc/redis/redis.conf?

For me it seems a little messy lying in this folder.

Thank you and kind regards,

Tobias

**Comment by petems** [comment]
the redis.conf file in RedHat is /etc/redis.conf in the provided RPM:

%config(noreplace) %attr(0644, root, root) "/etc/logrotate.d/redis"
%config(noreplace) %attr(0644, redis, root) "/etc/redis-sentinel.conf"
%config(noreplace) %attr(0644, redis, root) "/etc/redis.conf"
If you wish to change it,

Changing the default param would be an breaking change to the module.

If you wish to provide a different path, you would just call the class with a different path:

class { 'redis':
  config_file => '/etc/redis/redis.conf',
}
As far as I can see from the module and reading the redis docs, there's no need for a config dir at all unless you're moving it from it's default location at /etc/redis.conf

See also via https://github.com/arioch/puppet-redis/pull/82
