### ISSUE TITLE
Error 400 on SERVER: Puppet::Parser::AST::Resource failed with error ArgumentError: Invalid resource type redis

### ISSUE THREAD

**Issue by aamerik** [arioch/puppet-redis#86]
Hello. I'm trying to use create_resources() or ensure_resource() with this module and I'm running into issues with resource type 'redis' not found issues.  I'm able to instantiate the module using "class { 'redis':}" but not with those two functioned mentioned.  Is this a known limitation? Thanks

**Comment by arioch** [comment]
Could you provide the manifest you're using and a verbose log of what's going wrong?

**Comment by aamerik** [comment]
Arioch,

My manifest looks like this:
```
class ops::redis::cache (
  $defaults   = 'UNSET',
  $instances = 'UNSET',
) {
  create_resources ('redis', $instances, $defaults)
}
```

And the resulting error is:

```
Info: Retrieving pluginfacts
Info: Retrieving plugin
Info: Loading facts
Error: Could not retrieve catalog from remote server: Error 400 on SERVER: Puppet::Parser::AST::Resource failed with error ArgumentError: Invalid resource type redis at /etc/puppet/environments/qa3/modules/ops/manifests/redis/cache.pp:5 on node cache003.qa3.ca3.foo.co
Warning: Not using cache on failed catalog
Error: Could not retrieve catalog; skipping run
```

The missing type error is confusing because if I change my manifest to:
```
class ops::redis::cache (
) {
  class { 'redis': 
     package_name => 'ops-redis28',
  }
}
```
the catalog compiles and executes as expected.

Do you know if I need to wrap the redis class in a define to make create_resources work as expected?

Thank you!

**Comment by aamerik** [comment]
Didnt mean to close this. reopened.
