### ISSUE TITLE
Add support to custom repos with RedHat

### ISSUE THREAD

**Issue by vide** [arioch/puppet-redis#91]
Right now if you are using RHEL/CentOS, if you set the `manage_repo` option you are forced to use two hardcoded repos (depending on your major version). There should be a way, like with Ubuntu, to specify a custom repo.

**Comment by petems** [comment]
@vide Generally with modules you give the minimum required to get it working for a basic usecase.

If you want to use your own repos, set `manage_repo` to false and manage the yumrepo which handles Redis in your roles and profiles 

More details here: https://docs.puppet.com/pe/2016.2/r_n_p_intro.html
