### ISSUE TITLE
More cluster documentation

### ISSUE THREAD

**Issue by claflico** [arioch/puppet-redis#95]
Would it be possible to get a bit more explanation or examples on how to setup a 3 node redis 3.0 cluster? I'm trying to read through various tutorials online and they all show manual commands that must be ran to get the cluster started.

What's there is kind of confusing:

``` puppet
class { 'redis':
  bind                 => '10.0.1.2',
  appendonly           => true,
  cluster_enabled      => true,
  cluster_config_file  => 'nodes.conf',
  cluster_node_timeout => 5000,
}
```

I understand that bind is the ip of the node but do we still need to specify "slaveof" so that the two "slave" nodes connect to the master?

If we add "class { 'redis::sentinel':}" do we still need to add the redis class?

**Comment by petems** [comment]
A three node cluster can be setup thusly:

```puppet
$master_ip_address = '10.255.33.129'

node /redis-master/ {
service {'firewalld':
  ensure => 'stopped',
}

class { 'redis':
  manage_repo => true,
  bind                => $master_ip_address,
  requirepass   => 'foobared',
}
}
```

```
node /redis-slave-[\d]/ {
class { 'redis':
  manage_repo => true,
  bind                => $::ipaddress_enp0s8,
  masterauth    => 'foobared',
  slaveof           => "${master_ip_address} 6379"
}
```

This is demonstrated in the acceptance test `puppet-redis/spec/acceptance/redis_multi_node_spec.rb`, which is actually run on a 3 node Vagrant box test environment.

The sentinel is required if you want automatic failover with Sentinel also.

Does this answer your question? If so, I'll add it to the docs and PR it. 👍

**Comment by claflico** [comment]
Sorry, not really using this anymore as we've moved on to Docker. I'll go ahead and close it.

Thanks
